/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import 'ionicons';
import '@ionic/core';

import {
  EventEmitter,
} from '@stencil/core';

declare global {

  namespace StencilComponents {
    interface AppFirebase {

    }
  }

  interface HTMLAppFirebaseElement extends StencilComponents.AppFirebase, HTMLStencilElement {}

  var HTMLAppFirebaseElement: {
    prototype: HTMLAppFirebaseElement;
    new (): HTMLAppFirebaseElement;
  };
  interface HTMLElementTagNameMap {
    'app-firebase': HTMLAppFirebaseElement;
  }
  interface ElementTagNameMap {
    'app-firebase': HTMLAppFirebaseElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-firebase': JSXElements.AppFirebaseAttributes;
    }
  }
  namespace JSXElements {
    export interface AppFirebaseAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppGizmoDetail {

    }
  }

  interface HTMLAppGizmoDetailElement extends StencilComponents.AppGizmoDetail, HTMLStencilElement {}

  var HTMLAppGizmoDetailElement: {
    prototype: HTMLAppGizmoDetailElement;
    new (): HTMLAppGizmoDetailElement;
  };
  interface HTMLElementTagNameMap {
    'app-gizmo-detail': HTMLAppGizmoDetailElement;
  }
  interface ElementTagNameMap {
    'app-gizmo-detail': HTMLAppGizmoDetailElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-gizmo-detail': JSXElements.AppGizmoDetailAttributes;
    }
  }
  namespace JSXElements {
    export interface AppGizmoDetailAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppGizmo {

    }
  }

  interface HTMLAppGizmoElement extends StencilComponents.AppGizmo, HTMLStencilElement {}

  var HTMLAppGizmoElement: {
    prototype: HTMLAppGizmoElement;
    new (): HTMLAppGizmoElement;
  };
  interface HTMLElementTagNameMap {
    'app-gizmo': HTMLAppGizmoElement;
  }
  interface ElementTagNameMap {
    'app-gizmo': HTMLAppGizmoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-gizmo': JSXElements.AppGizmoAttributes;
    }
  }
  namespace JSXElements {
    export interface AppGizmoAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppHome {

    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppSignIn {

    }
  }

  interface HTMLAppSignInElement extends StencilComponents.AppSignIn, HTMLStencilElement {}

  var HTMLAppSignInElement: {
    prototype: HTMLAppSignInElement;
    new (): HTMLAppSignInElement;
  };
  interface HTMLElementTagNameMap {
    'app-sign-in': HTMLAppSignInElement;
  }
  interface ElementTagNameMap {
    'app-sign-in': HTMLAppSignInElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-sign-in': JSXElements.AppSignInAttributes;
    }
  }
  namespace JSXElements {
    export interface AppSignInAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface LazyImg {
      'alt': string;
      'src': string;
      'width': number;
    }
  }

  interface HTMLLazyImgElement extends StencilComponents.LazyImg, HTMLStencilElement {}

  var HTMLLazyImgElement: {
    prototype: HTMLLazyImgElement;
    new (): HTMLLazyImgElement;
  };
  interface HTMLElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  interface ElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'lazy-img': JSXElements.LazyImgAttributes;
    }
  }
  namespace JSXElements {
    export interface LazyImgAttributes extends HTMLAttributes {
      'alt'?: string;
      'onLazyImgloaded'?: (event: CustomEvent<HTMLImageElement>) => void;
      'src'?: string;
      'width'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface MyApp {

    }
  }

  interface HTMLMyAppElement extends StencilComponents.MyApp, HTMLStencilElement {}

  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-app': JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface PageFirebaseCloudFirestore {

    }
  }

  interface HTMLPageFirebaseCloudFirestoreElement extends StencilComponents.PageFirebaseCloudFirestore, HTMLStencilElement {}

  var HTMLPageFirebaseCloudFirestoreElement: {
    prototype: HTMLPageFirebaseCloudFirestoreElement;
    new (): HTMLPageFirebaseCloudFirestoreElement;
  };
  interface HTMLElementTagNameMap {
    'page-firebase-cloud-firestore': HTMLPageFirebaseCloudFirestoreElement;
  }
  interface ElementTagNameMap {
    'page-firebase-cloud-firestore': HTMLPageFirebaseCloudFirestoreElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'page-firebase-cloud-firestore': JSXElements.PageFirebaseCloudFirestoreAttributes;
    }
  }
  namespace JSXElements {
    export interface PageFirebaseCloudFirestoreAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface TjaexaModalForm {

    }
  }

  interface HTMLTjaexaModalFormElement extends StencilComponents.TjaexaModalForm, HTMLStencilElement {}

  var HTMLTjaexaModalFormElement: {
    prototype: HTMLTjaexaModalFormElement;
    new (): HTMLTjaexaModalFormElement;
  };
  interface HTMLElementTagNameMap {
    'tjaexa-modal-form': HTMLTjaexaModalFormElement;
  }
  interface ElementTagNameMap {
    'tjaexa-modal-form': HTMLTjaexaModalFormElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'tjaexa-modal-form': JSXElements.TjaexaModalFormAttributes;
    }
  }
  namespace JSXElements {
    export interface TjaexaModalFormAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface TjaexaShowModal {

    }
  }

  interface HTMLTjaexaShowModalElement extends StencilComponents.TjaexaShowModal, HTMLStencilElement {}

  var HTMLTjaexaShowModalElement: {
    prototype: HTMLTjaexaShowModalElement;
    new (): HTMLTjaexaShowModalElement;
  };
  interface HTMLElementTagNameMap {
    'tjaexa-show-modal': HTMLTjaexaShowModalElement;
  }
  interface ElementTagNameMap {
    'tjaexa-show-modal': HTMLTjaexaShowModalElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'tjaexa-show-modal': JSXElements.TjaexaShowModalAttributes;
    }
  }
  namespace JSXElements {
    export interface TjaexaShowModalAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
